### ISSUE TITLE
could the project be transferred to me? I am the developer of Shinobi

### ISSUE THREAD

**Issue by moeiscool** [moeiscool/homebridge-shinobi#29]
I would like to take ownership of this repository since it is currently no longer maintained. We would like to maintain it.

Also, please consider deleting (or transferring to me if possible) homebridge-shinobi from npmjs as well.

**Comment by vectronic** [comment]
Hi there. I’d be happy to! Give me a few days - I’m travelling at the moment.

**Comment by vectronic** [comment]
@moeiscool I am doing the transfer now. 

With respect to npm, let me know your username there and I will transfer that as well.

I had this working pretty well for my own purposes with no issues. Just occasional user tickets raised, mostly either due to people not following instructions or their Shinobi being setup differently to mine. 

I have moved to a different home security setup.

I think you will obviously be the right person to take this further!

**Comment by moeiscool** [comment]
Thank you greatly :) my profile on npmjs is here https://www.npmjs.com/~moeiscool

And thanks for starting this project :) cheers!

**Comment by edrikk** [comment]
Hi there,
How close to completion is this transfer?
Just checking because per above this isn't being maintained any longer, and I have found that the plugin doesn't work with the dev branch any longer - throwing errors.
Not sure if any implications as well in terms of the upcoming homebridge 2.0.

**Comment by vectronic** [comment]
@edrikk I have commenced the transfer to @moeiscool but it looks like he hasn't accepted it...

**Comment by moeiscool** [comment]
Sorry, I didn't see it, the email that would have notified me to accept was in my spam... 😅 i kindly request sending it again

**Comment by vectronic** [comment]
Transfer cancelled and restarted

**Comment by moeiscool** [comment]
accepted, thank you
